ARG BASE_IMAGE=${BASE_IMAGE}

# Build AUR packages
FROM localhost/trellis-builder AS pkg-builder

RUN build-aur --skippgpcheck wluma

FROM ${BASE_IMAGE} AS cosmic

# Install Arch packages
RUN pacman --noconfirm -S \
  cosmic \
	wlsunset \
	wofi \
	clipman \
	alacritty \
	ttf-firacode-nerd \
	xorg-xwayland \
	ddcutil

# Install built AUR packages.
COPY --from=pkg-builder /aur /aur
RUN pacman --noconfirm -U /aur/*
RUN rm -r /aur

# Setup greeter
RUN systemctl enable cosmic-greeter

