ARG BASE_IMAGE=${BASE_IMAGE}

# Build AUR packages
FROM localhost/trellis-builder AS pkg-builder
RUN build-aur \
  agent-deck

FROM ${BASE_IMAGE} AS cannopy

# Install Arch packages
RUN pacman --noconfirm -S \
	git-lfs \
	sshfs \
	base-devel \
	clang \
	lld \
	syncthing \
	wireguard-tools \
	qemu-guest-agent \
	mosh \
	rsync \
	fail2ban

# Install built AUR packages.
COPY --from=pkg-builder /aur /aur
RUN pacman --noconfirm -U /aur/*
RUN rm -r /aur

RUN systemctl enable qemu-guest-agent.service
