ARG BASE_IMAGE=${BASE_IMAGE}
FROM ${BASE_IMAGE} AS fwupd

# Install Arch packages
RUN pacman --noconfirm -S \
  fwupd \
  udisks2

# Enable usdisk2
RUN systemctl enable udisks2

# Disable locale cache server
RUN systemctl mask passim.service

