FROM localhost/archlinux-ostree-builder AS builder

# Install packages.
RUN pacstrap -c -G -M /mnt \
	base \
	linux \
	linux-firmware \
	dracut \
	intel-ucode \
	amd-ucode \
	efibootmgr \
	grub \
	ostree \
	podman \
	which \
	less \
	git \
	vim \
	iwd 

# Setup dracut
COPY rootfs/etc/dracut.conf.d/ostree.conf /mnt/etc/dracut.conf.d/
COPY rootfs/etc/dracut.conf.d/module-setup.sh /mnt/etc/dracut.conf.d/

# Build AUR packages: Install dependencies and create user.
RUN pacman --noconfirm -Syu base-devel git sudo
RUN useradd -m builder

# Build AUR packages: Build
USER builder
RUN git clone https://aur.archlinux.org/yay-bin.git /home/builder/yay-bin
RUN cd /home/builder/yay-bin && makepkg -s --noconfirm
USER root

# Build AUR packages: Copy packages to a common place.
RUN mkdir /aur
RUN cp /home/builder/yay-bin/*.tar.zst /aur/

# Turn the pacstrapped rootfs into a container image.
FROM scratch
COPY --from=builder /mnt /

# The rootfs can't be modified and systemd can't create them implicitly.
# That's why we have to create them as part of the rootfs.
RUN mkdir /efi

# Normal post installation steps.
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
RUN sed -i 's/^#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
RUN locale-gen
RUN systemctl enable systemd-timesyncd.service

# Install built AUR packages.
COPY --from=builder /aur /aur
RUN echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist
RUN pacman-key --init
RUN pacman-key --populate
RUN pacman --noconfirm -U /aur/*
RUN rm -r /aur

# Generate initramfs
COPY scripts/dracut-setup.sh /
RUN /dracut-setup.sh && ls /boot && rm /dracut-setup.sh
