FROM localhost/archlinux-ostree-builder AS builder

# Bootstrap early reuired packages.
RUN pacstrap -c -G -M /mnt \
	base \
	linux-firmware \
	dracut \
	intel-ucode \
	amd-ucode \
	wget

# Setup dracut
COPY rootfs/etc/dracut.conf.d/ostree.conf /mnt/etc/dracut.conf.d/
COPY rootfs/etc/dracut.conf.d/module-setup.sh /mnt/etc/dracut.conf.d/

# Build AUR packages: Install dependencies and create user.
RUN pacman --noconfirm -Syu base-devel git sudo
RUN useradd -m builder

# Build AUR packages: Build
USER builder
RUN git clone https://aur.archlinux.org/yay-bin.git /home/builder/yay-bin
RUN cd /home/builder/yay-bin && makepkg -s --noconfirm
USER root

# Build AUR packages: Copy packages to a common place.
RUN mkdir /aur
RUN cp /home/builder/yay-bin/*.tar.zst /aur/

# Turn the pacstrapped rootfs into a container image.
FROM scratch
COPY --from=builder /mnt /

# Switch to CachyOS repos
RUN echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist
RUN pacman-key --init
RUN pacman-key --populate
RUN wget https://mirror.cachyos.org/cachyos-repo.tar.xz && \
	tar xvf cachyos-repo.tar.xz && \
	cd cachyos-repo && \
	sed -i 's/pacman /pacman --noconfirm /g' cachyos-repo.sh && \
	./cachyos-repo.sh && \
	cd .. && \
	rm -rf cachyos-repo cachyos-repo.tar.xz

# Install packages
RUN pacman --noconfirm -S \
	linux-cachyos \
	efibootmgr \
	grub \
	ostree \
	podman \
	iwd \
	which \
	less \
	git \
	vim

# The rootfs can't be modified and systemd can't create them implicitly.
# That's why we have to create them as part of the rootfs.
RUN mkdir /efi

# Normal post installation steps.
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
RUN sed -i 's/^#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
RUN locale-gen
RUN systemctl enable systemd-timesyncd.service

# Enable networking
RUN systemctl enable systemd-networkd
RUN systemctl enable systemd-resolved
RUN systemctl disable systemd-networkd-wait-online

# Wireless networking
RUN systemctl enable iwd

# Install built AUR packages.
COPY --from=builder /aur /aur
RUN pacman --noconfirm -U /aur/*
RUN rm -r /aur

# Generate initramfs
COPY scripts/dracut-setup.sh /
RUN /dracut-setup.sh && ls /boot && rm /dracut-setup.sh
