ARG BASE_IMAGE=${BASE_IMAGE}

# Build portmaster from AUR
FROM localhost/trellis-builder AS pkg-builder
RUN build-aur \
  portmaster-bin

FROM ${BASE_IMAGE} AS portmaster
COPY --from=pkg-builder /aur /aur
RUN pacman -U --noconfirm /aur/*
RUN rm -r /aur

FROM ${BASE_IMAGE} as firewalld
RUN pacman -S --noconfirm firewalld && systemctl enable firewalld

